# See https://zsh.sourceforge.io/Intro/intro_3.html#SEC3
# zProfile is loaded for login shells before .zshrc
# Set user specific environment variables here

# Add home directory bin to path
export PATH=$PATH:~/bin

# TODO: Move this somewhere else (possibly tools) instead of profile
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
