# See https://zsh.sourceforge.io/Intro/intro_3.html#SEC3
# zProfile is loaded for login shells before .zshrc
# Set user specific environment variables here


# TODO: The following lines should be moved or restructured
export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/9.5/bin
export PATH=$PATH:/Applications/Sublime\ Text.app/Contents/SharedSupport/bin

export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)

export PATH="$HOME/.cargo/bin:$PATH"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
