# Oh-My-Zsh Installation
source $DOTFILES/zsh/oh-my-zsh.zsh

#### Start Base Zsh Configuration
# User configuration

## You may need to manually set your language environment
export LANG=en_US.UTF-8

## Setup Programing Languages
source $DOTFILES/zsh/languages.zsh

## Set user aliases
source $DOTFILES/zsh/aliases.zsh

### Load configs for Tools, Projects and Apps
# Pass false to avoid reinstalling tools which slow shell startup
source $DOTFILES/zsh/install-tools.zsh false


### Unused configs
# export MANPATH="/usr/local/man:$MANPATH"

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

#### End Base Zsh Configuration
